# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0006_auto_20180917_1720'),
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
