# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0002_auto_20180917_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cname',
            field=models.CharField(max_length=20, verbose_name='评论用户'),
        ),
    ]
