# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20180917_1656'),
        ('bloginfo', '0004_blog_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20, verbose_name='收藏作者姓名')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloginfo.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Userinfo')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'save',
            },
        ),
    ]
