# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0011_remove_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='morenzhi', on_delete=django.db.models.deletion.CASCADE, to='bloginfo.Category', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
