# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0012_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorya',
        ),
        migrations.AlterModelTable(
            name='categorya',
            table='categorya',
        ),
    ]
