# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0013_auto_20180917_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
