# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloginfo', '0015_delete_categorya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
