# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '登录用户', 'verbose_name_plural': '登录用户'},
        ),
    ]
