# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20180917_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
